InventoryManagementSystem/Models/ProcessOrderModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace InventoryManagementSystem.Models
{
    public class ProcessOrderModel
    {
        public string Id { get; set; }
        public string ProductId { get; set; }
        public int Quantity { get; set; }
    }
}

InventoryManagementSystem/Controllers/ProcessOrderController.cs
using InventoryManagementSystem.Domain;
using InventoryManagementSystem.Models;
using InventoryManagementSystem.Repository;
using System.Web.Mvc;

namespace InventoryManagementSystem.Controllers
{
    public class ProcessOrderController : Controller
    {

        // GET: ProcessOrder
        public ActionResult Index()
        {
            return View();
        }

        // GET: ProcessOrder/Details/5
        public ActionResult Details(int id)
        {
            return View();
        }

        // GET: ProcessOrder/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: ProcessOrder/Create
        [HttpPost]
        public ActionResult Create(ProcessOrderModel request)
        {
            try
            {
                IProcessOrderRepository processOrderRepository = new ProcessOrderRepo();
                var isOrderCreated = processOrderRepository.ProcessOrder(request.ProductId, request.Quantity);
                if (isOrderCreated)
                    return RedirectToAction("Index");
                else
                {
                    return View("Failure");
                }

            }
            catch
            {
                return View();
            }
        }


    }
}

InventoryManagementSystem/Views/ProcessOrder/Create.cshtml
@model InventoryManagementSystem.Models.ProcessOrderModel

@{
    ViewBag.Title = "Create";
}

@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>ProcessOrderModel</h4>

        <hr />
        Note: Please enter qty is double of the productid value, For ex if product Id is 4 then qty should be 8 ...
        (product id should be less than 10)
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.ProductId, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.ProductId, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.ProductId, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Quantity, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Quantity, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Quantity, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}


@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

InventoryManagementSystem/Views/ProcessOrder/Failure.cshtml
@{
    ViewBag.Title = "Failure";
}

<h2>product is not available in the store</h2>

@Html.ActionLink("Back", "Create")

InventoryManagementSystem/Views/ProcessOrder/Index.cshtml
@{
    ViewBag.Title = "Index";
}

<h2>Order Processed Successfullyyyy</h2>

@Html.ActionLink("Back", "Create")

InventoryManagementSystem/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - Inventory Management System</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Inventory Management System", "Create", "ProcessOrder", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("Order Process", "Create", "ProcessOrder")</li>
                </ul>
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - Inventory Management System</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>